esphome:
  name: esp32-s3-zero-test
  friendly_name: esp32-s3-zero-test

  platformio_options:
    board_build.f_flash: 40000000L
    board_build.flash_mode: dio
    board_build.flash_size: 4MB

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y
      CONFIG_BT_BLE_50_FEATURES_SUPPORTED: n

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "qE80lkl61SuTa8jjPEci379zGzxaePHz8sYKBGTA2Q0="

ota:
  - platform: esphome
    password: "917a73e1b09d0556cccab787cd1e6680"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "XXXX"
    password: "XXXX"

  output_power: 8.5dB # fix for S3 zero reboot issue

captive_portal:

sensor:
  - platform: wifi_signal
    name: "WiFi signal strength"
    update_interval: 30s

  - platform: uptime
    name: "Uptime"
    filters:
      - lambda: return x / 3600.0;
    unit_of_measurement: "hours"
    icon: mdi:clock-start
    accuracy_decimals: 2

  - platform: internal_temperature
    name: "Internal temperature"
    update_interval: 20s

button:
  - platform: restart
    name: "Restart"

light:
  - platform: esp32_rmt_led_strip
    rgb_order: GRB
    pin: GPIO21
    num_leds: 1
    rmt_channel: 0
    chipset: ws2812
    name: "Board LED"